### ISSUE TITLE
[논의] REST API URI and Method

### ISSUE THREAD

**Issue by f-lab-kane** [f-lab-edu/AYU-Coupon-Service#60]
## 배경
- 이번 프로젝트에서 개발하는 Api 들에 대해 uri와 method에 대해 정리하고 넘어가고자 합니다.

## 진행할 작업

- @cire0304 님, 개발에 필요한 전체 api에 대해 api별 uri와 method를 다시한번 고민해보시고 정리해주시면 감사하겠습니다.
- 아래 코멘트로 작성해주시면 됩니다.

**Comment by cire0304** [comment]
## 개발 API

http header에 들어가는 `user-id`는 생략했습니다.

- user-id

### 전체 쿠폰 조회 API

method & uri :  GET  /coupons

===

### 나의 쿠폰 목록 조회API

method 및 uri : URI :  GET  /users/coupons

===

### 쿠폰 발급 API

method 및 uri : POST  /users/coupons

**http body**

- couponId

**응답 코드**

- 201(CREATED)

쿠폰 발급 API는 사용자의 쿠폰을 `추가하는 행위`라고 생각합니다.
따라서 사용자의 쿠폰을 식별하는 uri /users/coupons, 자원을 추가하는 행위를 POST mothod로 표현하였습니다.

===

### 쿠폰 사용 API

method 및 uri : URI :  PATCH  /users/coupons/{couponId}

쿠폰 사용 API는  쿠폰의 일부 상태를 변경(UNUSED -> USED)하는 API이기 때문에 PATCH method를 사용하였습니다.

**Comment by f-lab-kane** [comment]
@cire0304 님, 의견 드립니다.
우선 앞서 얘기드린거처럼 공통적으로 version 정보는 들어가면 좋을거 같아요.

> ### 전체 쿠폰 목록 조회 API
> method & uri : GET /coupons

- 해당 api에서는 공통사항(version) 외에는 이견 없습니다.

> ### 나의 쿠폰 목록 조회API
> method 및 uri : URI : GET /users/coupons

- method에는 이견 없습니다.
- restful 설계 원칙과 규칙을 고려한다면 /users/coupons 는 일반적으로 모든 사용자의 쿠폰을 조회하는 api로 해석될 수 있습니다.
- 멘토링때 말씀 드린거처럼 특정 사용자의 쿠폰을 조회하는 경우 /users/{user_id}/coupons 가 되어야 할것이에요. 하지만 저희가 user_id를 header값으로 전달 받기로 했고 인증된 사용자의 의미를 담는다면, `/me/coupons` or `/my/coupons` 가 될수 있을거 같습니다.

> ### 쿠폰 발급 API
> method 및 uri : POST /users/coupons
> 
> **http body**
> 
> * Coupon-Id
> 
> **응답 코드**
> 
> * 201(CREATED)
> 
> 쿠폰 발급 API는 사용자의 쿠폰을 `추가하는 행위`라고 생각합니다. 따라서 사용자의 쿠폰을 식별하는 uri /users/coupons, 자원을 추가하는 행위를 POST mothod로 표현하였습니다.

- method에는 이견 없습니다.
- 쿠폰 목록 조회 api 와 마찬가지로 `/users`는 모든 사용자의 의미로 해석될수 있을거 같습니다.
- 추가적으로 리소스를 표현하는 관점에서 생각해볼때 `/me/user-coupons` 가 되어야 할지 고민해볼 필요성이 있습니다. `/me/coupons`로도 충분히 표현이 적절하지만 향후 사용자에게 발급된 쿠폰('user-coupon' 엔티티)와 관련된 추가 기능이나 엔드포인트를 개발할 필요가 있을 때, `/me/user-coupons` 기반의 url 구조가 확장하기에 더 적합하지 않을까 생각되요.

> ### 쿠폰 사용 API
> method 및 uri : URI : PATCH /users/coupons/{couponId}
> 
> 쿠폰 사용 API는 쿠폰의 일부 상태를 변경(UNUSED -> USED)하는 API이기 때문에 PATCH method가 가장 적합하다 생각합니다.

- method에는 이견 없습니다.
- 쿠폰 목록 조회 api 와 마찬가지로 `/users`는 모든 사용자의 의미로 해석될수 있을거 같습니다.
- 추가적으로 쿠폰발급 api에서 언급드린 사유와 동일한 관점에서 `/me/user-coupons/{user_coupon_id}` 의견 드려봅니다.
- request body에 "productPrice" 필드도 필요하겠네요.
```json
{
    "productPrice": 15000
}
```

rest api를 설계하는 과정에 있다고 생각해주시고 동준님의 의견을 추가적으로 달아주시면 좋을거 같습니다.

**Comment by cire0304** [comment]
케인님의 의견에 동의합니다.
- `/user/coupons` url은 여러가지 의미로 해석될 수 있기 때문에 restful 하지 못한 것 같습니다.
- **발급 중**인 쿠폰과 **발급 받은** 쿠폰의 자원은 **생성 및 수정 주기**가 완전히 다른 자원입니다.
  - 따라서 두 개의 자원을 별개의 자원으로 생각하여, url 명을 결정하는 것이 맞다고 생각합니다.

===
 
rest api url을 정할 때, 가장 중요한것은 다음과 같다고 생각합니다.
- 자원을 명확하게 표현해야한다.
- 일관된 구조를 가져야 한다.
- 확장성있는 구조를 가져야 한다.

따라서 api url을 다음과 같이 정하면 어떨까 합니다.
- 전체 쿠폰 목록 조회 : `/v1/coupons` (GET)
- 특정 쿠폰 쿠폰 발급 : `/v1/coupons/{coupon_id}` (POST)
- 나의 쿠폰 목록 조회 : `/v1/users/me/user-coupons` (GET)
- 나의 쿠폰 사용 : `/v1/users/me/user-coupons/{user_coupon_id}` (PATCH)

### url에 `/users`을 붙인 이유

1. 자원을 좀 더 명확하게 표현하기 위해

`/users`를 **prefix**로 사용함으로써 `사용자들 중 자기자신`이라는 자원을 좀 더 명확히 표현할 수 있을 것 같습니다.
물론 `/me`만으로 충분히 자원을 표현할 수 있기 때문에, **중복된 표현**이라고 생각될 여지는 있는 것 같습니다.

2. ** 확장성** 있는 구조 및 **일관된** 구조를 가지기 위해

만약 사용자의 자원과 관련된 api가 있다면, url의 **prefix**로 `**/users`를 사용할 것 같습니다.
그리고 `나의 쿠폰 사용` api는 사용자의 자원과 관련된 api라고 생각합니다.

위와 같은 이유로 api url 명을 생각해 보았습니다. (http body은 생략하였습니다.)

위의 의견이 합당할까요?

**Comment by f-lab-kane** [comment]
@cire0304 님, 의견 감사해요.

> 따라서 api url을 다음과 같이 정하면 어떨까 합니다.
> 
> * 전체 쿠폰 목록 조회 : `/v1/coupons` (GET)
> * 특정 쿠폰 쿠폰 발급 : `/v1/coupons/{coupon_id}` (POST)
> * 나의 쿠폰 목록 조회 : `/v1/users/me/issued-coupons` (GET)
> * 나의 쿠폰 사용 : `/v1/users/me/issued-coupons/{issued_coupon_id}` (PATCH)

#### 1. /users/me 에 관하여
- 자원의 계층 구조 관점에서 생각해본다면 `/users/me` 도 선택지가 될수 있다고 생각합니다. `/me`로 의견드린 이유는 제가 경험했던 회사 포함 많은 회사들이 이렇게 사용중이더라구요. (참고. https://stackoverflow.com/questions/59850723/does-the-facebook-graph-api-have-a-me-resource)

#### 2. /issued-coupons 에 관하여

> user-coupon라는 표현이 발급 받은 쿠폰 이라는 자원을 충분히 설명하고 있는지는 좀 더 생각해볼만 한 것 같습니다.
> 명시적으로 발급 받은 쿠폰이라는 자원을 표현하기 위해 /issued-coupons을 사용하는 것은 어떨까요?

실제 서버에서 정의한 도메인의 리소스 이름은 user-coupon 입니다. 자원을 충분히 표현하고 있지 않다고 생각되어 다시 고민이 필요하다면, 테이블과 entity 이름도 함께 재고해보시면 좋을거 같습니다. 처음 설계할때 리소스 이름을 잘못 선택했다는 뜻이 될수도 있겠네요.

#### 3. 특정 쿠폰 쿠폰 발급 : `/v1/coupons/{coupon_id}` (POST) 에 관하여

특정 사용자의 나의 쿠폰 발급 기능으로 이해하고 있었는데 아닐까요?

> * 특정 쿠폰 쿠폰 발급 : `/v1/coupons/{coupon_id}` (POST)
> * 나의 쿠폰 목록 조회 : `/v1/users/me/issued-coupons` (GET)
> * 나의 쿠폰 사용 : `/v1/users/me/issued-coupons/{issued_coupon_id}` (PATCH)

- 사용자 쿠폰 발급 : POST `/v1/me/user-coupons` vs `/v1/me/coupons`
- 사용자 쿠폰 목록 조회 : GET `/v1/me/user-coupons` vs `/v1/me/coupons`
- 사용자 쿠폰 사용 : PATCH `/v1/me/user-coupons` vs `/v1/m/coupons/{coupon_id}`

> `/me`와 `user-coupons`는 예시 작성을 위해 임의로 기술하였습니다.

- 전자와 후자에 대해서 고민해보았습니다.
- 전자는 리소스 명을 명확하게 표현하고 있기 때문에 데이터 모델의 명확성 측면에서 적절할수 있습니다.
- 후자는 `내 쿠폰`이라는 개념을 바로 반영하기 때문에 API 사용자의 직관성 측면에서 적절할수 있습니다.

하지만 후자로 할 경우 coupon_id가 필요하기때문에 동준님이 생각하신 /v1/me/coupons/{coupon_id} 처럼 pathvariable로 coupon_id를 추가하는것에 고민을 하게 되는데 post의 경우 리소스를 생성하는 역할이기 때문에 보통 식별자를 포함시키지 않는것이 일반적입니다. 실제 리소스는 coupon 이 아니기에 발생하는 딜레마인거죠. 

확장성과 일관성, 유지보수성 측면에서 결정하면 좋을거 같아요. 금일 멘토링 시간에 구두로 논의해서 저희만의 최적의 결론을 내봐요ㅎ

**Comment by cire0304** [comment]
> 3. 특정 쿠폰 쿠폰 발급 : /v1/coupons/{coupon_id} (POST) 에 관하여
아 최근 코멘트를 제가 잘못 작성했습니다. `/users/me/issued-coupons (POST)` 가 맞습니다.

> 확장성과 일관성, 유지보수성 측면에서 결정하면 좋을거 같아요. 금일 멘토링 시간에 구두로 논의해서 저희만의 최적의 결론을 내봐요ㅎ
넵 알겠습니다 😆

**Comment by cire0304** [comment]
맨토링에서의 논의 후 최종 API URL입니다.

- 전체 쿠폰 목록 조회 : /v1/coupons?page={page} (GET)
- 특정 쿠폰 쿠폰 발급 : /v1/users/me/user-coupons (POST)
- 나의 쿠폰 목록 조회 : /v1/users/me/user-coupons (GET)
- 나의 쿠폰 사용 : /v1/users/me/user-coupons/{user_coupon_id} (PATCH)

전체 쿠폰 목록 조회 url에 페이지를 표현하기 위해, Query parameter page를 추가하였습니다.
- 페이지의 기본 사이즈는 10으로 설정

발급된 사용자 쿠폰의 자원명을 `user-couopns`로 결정했습니다.
- 발급된 유저 쿠폰의 표현을 충분히 표현하고 있다고 판단
- 이미 서버에서 **발급된 사용자 쿠폰 도메인 자원의 이름**이 `UserCoupon`으로 개발됨

**Comment by cire0304** [comment]
restful url가 확정되어, 해당 이슈를 close 합니다.
